apiVersion: apps/v1
kind: Deployment

metadata:
  name: brain-tasks-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: brain-tasks-app

  template:
    metadata:
      labels:
        app: brain-tasks-app

    spec:
      containers:
        - name: brain-tasks-app

          image: 251478238401.dkr.ecr.us-east-2.amazonaws.com/brain-tasks-app:latest

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 80

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 80

            initialDelaySeconds: 10
            periodSeconds: 20
